version: '3.8'

services:
  tradingsystem:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/library/tradingsystem-tradingsystem
    container_name: tradingsystem
    restart: unless-stopped
    networks:
      - trading-network
    depends_on:
      - postgres
      - redis
      - timescaledb

  postgres:
    image: postgres:14.5-alpine
    container_name: trading-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - trading-network

  redis:
    image: redis:7.0-alpine
    container_name: trading-redis
    restart: unless-stopped
    networks:
      - trading-network

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: trading-timescaledb
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - trading-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: trading-pgadmin
    restart: unless-stopped
    networks:
      - trading-network

  mailhog:
    image: mailhog/mailhog
    container_name: trading-mailhog
    restart: unless-stopped
    networks:
      - trading-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: trading-redis-commander
    restart: unless-stopped
    networks:
      - trading-network

networks:
  trading-network:
    name: trading-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
