apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    jsonData:
      timeInterval: "15s"
      queryTimeout: "30s"
      httpMethod: "POST"
      manageAlerts: true
      prometheusType: "Prometheus"
      prometheusVersion: "2.40.0"
      exemplarTraceIdDestinations:
        - name: "trace_id"
          datasourceUid: "tempo"
    secureJsonData: {}

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    database: "logs-*"
    url: http://elasticsearch:9200
    jsonData:
      timeField: "@timestamp"
      esVersion: "8.0.0"
      maxConcurrentShardRequests: 5
      logMessageField: "message"
      logLevelField: "level"

  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: tradingsystem
    user: ${DB_USER}
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      sslmode: "disable"
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      postgresVersion: 1400
      timescaledb: false

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      nodeGraph:
        enabled: true
      lokiSearch:
        enabled: true
      serviceMap:
        enabled: true
      spanBar:
        type: "duration"
      search:
        hide: false
      lokiSearchEnabled: true
      tracesToLogs:
        datasourceUid: "loki"
        tags: ["job", "instance", "pod", "namespace"]
        mappedTags: ["level"]
        mapTagNamesEnabled: true
        spanStartTimeShift: "-1m"
        spanEndTimeShift: "1m"
        filterByTraceID: true
        filterBySpanID: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: "trace_id"
          matcherRegex: "trace_id=(\\w+)"
          url: "${__value.raw}"
          datasourceUid: "tempo"
        - name: "span_id"
          matcherRegex: "span_id=(\\w+)"
          url: "${__value.raw}"
          datasourceUid: "tempo"

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis:6379
    secureJsonData:
      password: ${REDIS_PASSWORD}
    jsonData:
      client: "standalone"
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
